ALTER TABLE TABLE_CONTRACTS
ADD id_employee INTEGER NOT NULL,
ADD id_company INTEGER NOT NULL;

ALTER TABLE TABLE_CONTRACTS
ADD FOREIGN KEY (id_employee) REFERENCES TABLE_EMPLOYEES (id),
ADD FOREIGN KEY (id_company) REFERENCES TABLE_COMPANIES (id);