CREATE TABLE TABLE_EMPLOYEES
(
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	full_name VARCHAR(100) NOT NULL,
	email VARCHAR(80) NOT NULL UNIQUE,
	agency VARCHAR(8) NOT NULL,
	checking_account VARCHAR(15) NOT NULL UNIQUE
) 