CREATE TABLE TABLE_EMPLOYEES_COMPANIES (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	id_employee INTEGER NOT NULL,
	id_company INTEGER NOT NULL,
	FOREIGN KEY (id_employee) REFERENCES TABLE_EMPLOYEES(id),
	FOREIGN KEY (id_company) REFERENCES TABLE_COMPANIES(id)
)