CREATE TABLE TABLE_CONTRACTS_EMPLOYEES
(
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	id_contract INTEGER NOT NULL UNIQUE KEY,
	id_employee INTEGER NOT NULL,
	FOREIGN KEY (id_contract) REFERENCES TABLE_CONTRACTS (id),
	FOREIGN KEY (id_employee) REFERENCES TABLE_EMPLOYEES (id)
)