CREATE TABLE TABLE_TRANSACTIONS_COMPANIES
(
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	id_transaction INTEGER NOT NULL UNIQUE KEY,
	id_company INTEGER NOT NULL,
	FOREIGN KEY (id_transaction) REFERENCES TABLE_TRANSACTIONS (id),
	FOREIGN KEY (id_company) REFERENCES TABLE_COMPANIES (id)
)